spring:
  datasource:
    url: jdbc:mysql://112.74.192.192:3306/attenddb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: sztvis@com.6789
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
server:
  port: 8084
storage:
  filepath: F:\YTBUS\storage\
staticUrl: http://192.168.0.9:8082/photo/
logging:
  level:
    com.sztvis.push.mapper: debug

